### PR TITLE
fix proptypes

### PR DESCRIPTION
**Pull request by st0ffern**
Fix for proptypes

Closes: #2

### CODE REVIEW

**Comment by gre** [comment]
thanks! it also looks like this lib is still on v2. i should port it to v3 and release a new major

**Comment by st0ffern** [comment]
thanks. Just a question i have been offline for a few months. Is the v3 completely diffrent from v2?
Is there a tutorial or information on how to convert from v2 to v3 ?

**Comment by gre** [comment]
it is not much different. it is mainly a simplification and optimisation of the internal implementation. maybe see http://greweb.me/2016/12/gl-react-v3/

**Comment by gre** [comment]
it allows to do backbuffering, it have the new Bus to "factorize" a rendering (aka express a graph instead of a tree), and other things..

**Pull request merged**
